sudo: required
language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -U setuptools
  - python setup.py install easy_install[testing]
# command to run tests
script:
  - nosetests
