language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -U setuptools mypy
  - python setup.py testing
# command to run tests
script:
  - pytest
  - mypy --ignore-missing-imports smscom
